
`timescale 1ns / 1ps

module dma_periph_src_model #(
    parameter RANDOM_WAIT = 0,
    parameter MAX_WAIT    = 3,
    parameter SEED        = 32'h0000_0000
) (
    input  wire        clk,
    input  wire        rst_n,      // synchronous active-low reset
    input  wire        sel,        // 1 = this model is the active responder
                                    // (tb's use_periph_src). Gates counting
                                    // so ren pulses generated by unrelated
                                    // mem-to-mem tests (src_ren is shared
                                    // across all source-side models) do not
                                    // silently advance this model's beat
                                    // counter ahead of where a later,
                                    // actually-selected test expects it.
    input  wire        ren,
    output reg  [31:0] rdata,
    output reg         ready
);

    reg [31:0] beat_count;
    reg [7:0]  wait_left;
    reg        pending;
    reg        armed;   // 1 = allowed to accept a new request on this ren
                         // level. Cleared the cycle a request is accepted;
                         // only re-set once ren is observed low. Without
                         // this, the one extra cycle ren stays high after
                         // ready pulses (the requester's ren-drop is itself
                         // registered, one cycle behind) would be seen as a
                         // second, phantom request and silently advance
                         // beat_count - harmless for address-indexed memory
                         // models (a repeat read of the same address is a
                         // no-op) but a real bug for a sequential counter.

    always @(posedge clk) begin
        if (!rst_n) begin
            beat_count <= 32'd0;
            wait_left  <= 8'd0;
            pending    <= 1'b0;
            ready      <= 1'b0;
            rdata      <= SEED;
            armed      <= 1'b1;
        end else begin
            ready <= 1'b0;
            if (!ren) begin
                armed <= 1'b1;
            end
            if (ren && sel && armed && !pending) begin
                armed <= 1'b0;
                if (RANDOM_WAIT) begin
                    wait_left <= ({$random} % MAX_WAIT);
                    pending   <= 1'b1;
                end else begin
                    ready      <= 1'b1;
                    rdata      <= SEED + beat_count;
                    beat_count <= beat_count + 32'd1;
                end
            end else if (pending) begin
                if (wait_left == 8'd0) begin
                    ready      <= 1'b1;
                    rdata      <= SEED + beat_count;
                    beat_count <= beat_count + 32'd1;
                    pending    <= 1'b0;
                end else begin
                    wait_left <= wait_left - 8'd1;
                end
            end
        end
    end

endmodule


module dma_periph_dst_model #(
    parameter RANDOM_WAIT = 0,
    parameter MAX_WAIT    = 3,
    parameter DEPTH       = 1024   // max beats this model can capture
) (
    input  wire        clk,
    input  wire        rst_n,     // synchronous active-low reset
    input  wire        sel,       // 1 = this model is the active responder
                                   // (tb's use_periph_dst). Gates capture so
                                   // wen pulses generated by unrelated
                                   // mem-to-mem tests (dst_wen is shared
                                   // across all destination-side models) do
                                   // not silently advance capture_idx ahead
                                   // of where a later, actually-selected
                                   // test expects it.
    input  wire [31:0] wdata,
    input  wire        wen,
    output reg         ready
);

    reg [31:0] captured [0:DEPTH-1];
    reg [31:0] capture_idx;
    reg [7:0]  wait_left;
    reg        pending;
    reg        armed;   // see matching comment in dma_periph_src_model above

    always @(posedge clk) begin
        if (!rst_n) begin
            capture_idx <= 32'd0;
            wait_left   <= 8'd0;
            pending     <= 1'b0;
            ready       <= 1'b0;
            armed       <= 1'b1;
        end else begin
            ready <= 1'b0;
            if (!wen) begin
                armed <= 1'b1;
            end
            if (wen && sel && armed && !pending) begin
                armed <= 1'b0;
                if (RANDOM_WAIT) begin
                    wait_left <= ({$random} % MAX_WAIT);
                    pending   <= 1'b1;
                end else begin
                    ready                    <= 1'b1;
                    captured[capture_idx]    <= wdata;
                    capture_idx              <= capture_idx + 32'd1;
                end
            end else if (pending) begin
                if (wait_left == 8'd0) begin
                    ready                    <= 1'b1;
                    captured[capture_idx]    <= wdata;
                    capture_idx              <= capture_idx + 32'd1;
                    pending                  <= 1'b0;
                end else begin
                    wait_left <= wait_left - 8'd1;
                end
            end
        end
    end

endmodule

